/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package eu.anmore.emed.mobi.test;

public final class R {
	public static final class array {
		public static final int roboguice_modules = 0x7f060000;
	}

	public static final class attr {
	}

	public static final class color {
		public static final int error_message_text_color = 0x7f040000;
	}

	public static final class dimen {
		public static final int patientList_patientListListView_row_displayNameSize = 0x7f050000;
		public static final int patientList_patientListListView_width = 0x7f050001;
	}

	public static final class drawable {
		public static final int icon = 0x7f020000;
	}

	public static final class id {
		public static final int loginPresenter_loginButton = 0x7f090004;
		public static final int loginPresenter_passwordEditText = 0x7f090002;
		public static final int loginPresenter_passwordErrorMessageTextView = 0x7f090003;
		public static final int loginPresenter_usernameEditText = 0x7f090000;
		public static final int loginPresenter_usernameErrorMessageTextView = 0x7f090001;
		public static final int menu_sutb_network = 0x7f090009;
		public static final int patientListPresenter_patientListListView = 0x7f090005;
		public static final int patientListPresenter_patientListListView_row_patientDisplayName = 0x7f090007;
		public static final int patientListPresenter_patientListListView_row_patientId = 0x7f090008;
		public static final int patientListPresenter_textHolderTextView = 0x7f090006;
	}

	public static final class layout {
		public static final int login = 0x7f030000;
		public static final int patient_list = 0x7f030001;
		public static final int patient_list_row = 0x7f030002;
	}

	public static final class menu {
		public static final int menu = 0x7f080000;
	}

	public static final class string {
		public static final int app_name = 0x7f070001;
		public static final int connection_error = 0x7f070002;
		public static final int connections_stub_off = 0x7f070004;
		public static final int connections_stub_on = 0x7f070003;
		public static final int empty_password_error = 0x7f070009;
		public static final int empty_username_error = 0x7f070008;
		public static final int hello = 0x7f070000;
		public static final int login = 0x7f070007;
		public static final int password = 0x7f070006;
		/**
		 * patient_list_activity
		 */
		public static final int patient_list = 0x7f07000b;
		/**
		 * login activity
		 */
		public static final int username = 0x7f070005;
		public static final int wrong_user_credentials = 0x7f07000a;
	}
}
