insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_ALBUMINALU', 'Albumina ludzka 20%');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_ALBUMINALU', 'Albumina ludzka 20%');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_ALDACTONE', 'Aldactone');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_ALDACTONE', 'Aldactone');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_AMBROHEXAL', 'Ambrohexal');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_AMBROHEXAL', 'Ambrohexal');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_ARDUAN', 'Arduan');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_ARDUAN', 'Arduan');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_BIODACYNA', 'Biodacyna');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_BIODACYNA', 'Biodacyna');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_BIOFUROKSY', 'Biofuroksym');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_BIOFUROKSY', 'Biofuroksym');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_CEFTRIAKSO', 'Ceftriakson');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_CEFTRIAKSO', 'Ceftriakson');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_CORDARONE', 'Cordarone');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_CORDARONE', 'Cordarone');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_CORHYDRON', 'Corhydron');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_CORHYDRON', 'Corhydron');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_COROTROPE', 'Corotrope');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_COROTROPE', 'Corotrope');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_CYCLONAMIN', 'Cyclonamine');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_CYCLONAMIN', 'Cyclonamine');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_DOBUTAMINE', 'Dobutamine');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_DOBUTAMINE', 'Dobutamine');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_DOLCONTRAL', 'Dolcontral');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_DOLCONTRAL', 'Dolcontral');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_FENTANYL', 'Fentanyl');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_FENTANYL', 'Fentanyl');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_FORTUM', 'Fortum');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_FORTUM', 'Fortum');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_FUROSEMIDU', 'Furosemidum');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_FUROSEMIDU', 'Furosemidum');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_GARDENAL', 'Gardenal');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_GARDENAL', 'Gardenal');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_GLUCOSUM10', 'Glucosum 10%');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_GLUCOSUM10', 'Glucosum 10%');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_GLUCOSUM20', 'Glucosum 20%');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_GLUCOSUM20', 'Glucosum 20%');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_HEPA-MERZ', 'Hepa-Merz');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_HEPA-MERZ', 'Hepa-Merz');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_HEPARIN', 'Heparin');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_HEPARIN', 'Heparin');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_IMIPENEMUM', 'Imipenemum/Cilastatinum Hospira');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_IMIPENEMUM', 'Imipenemum/Cilastatinum Hospira');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_INJ.ADRENA', 'Inj. Adrenalini 0,1%');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_INJ.ADRENA', 'Inj. Adrenalini 0,1%');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_KETONAL', 'Ketonal');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_KETONAL', 'Ketonal');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_MIDANIUM', 'Midanium');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_MIDANIUM', 'Midanium');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_MORPHINISU', 'Morphini sulfas');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_MORPHINISU', 'Morphini sulfas');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_NACL09', 'NaCl 0,9%');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_NACL09', 'NaCl 0,9%');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_NATRIUMBIC', 'Natrium bicarbonicum 8,4%');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_NATRIUMBIC', 'Natrium bicarbonicum 8,4%');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_NITROPRUSS', 'Nitropr Ussiat Fides');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_NITROPRUSS', 'Nitropr Ussiat Fides');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_PARACETAMO', 'Paracetamol');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_PARACETAMO', 'Paracetamol');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_PRIMENE10', 'Primene 10%');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_PRIMENE10', 'Primene 10%');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_PROPRANOLO', 'Propranolol');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_PROPRANOLO', 'Propranolol');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_PROSTINVR', 'Prostin VR');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_PROSTINVR', 'Prostin VR');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_ROCURONIUM', 'Rocuronium');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_ROCURONIUM', 'Rocuronium');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_SUFENTANYL', 'Sufentanyl');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_SUFENTANYL', 'Sufentanyl');
insert into observations_groups (group_key, type, visible_name) values ('WLEWY', 'W_TARFAZOLIN', 'Tarfazolin');
insert into observations_groups (group_key, type, visible_name) values ('BOLUSY', 'B_TARFAZOLIN', 'Tarfazolin');